-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS public.blockedusers
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    blocked_user_id uuid NOT NULL,
    CONSTRAINT blockedusers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.certifications
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    issuing_organization character varying(255) COLLATE pg_catalog."default" NOT NULL,
    issue_date date NOT NULL,
    expiration_date date,
    credential_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT certifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id uuid NOT NULL,
    post_id uuid NOT NULL,
    user_id uuid NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    edited_at timestamp without time zone NOT NULL DEFAULT now(),
    parent_comment_id uuid,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.companypages
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    industry character varying(100) COLLATE pg_catalog."default" NOT NULL,
    logo_url character varying(255) COLLATE pg_catalog."default",
    organization_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    website character varying(255) COLLATE pg_catalog."default",
    size character varying(20) COLLATE pg_catalog."default" NOT NULL,
    location character varying(100) COLLATE pg_catalog."default",
    admin_user_id uuid,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    about text COLLATE pg_catalog."default",
    cover_photo_url character varying(255) COLLATE pg_catalog."default",
    follower_count integer NOT NULL DEFAULT 0,
    CONSTRAINT companypages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.connections
(
    id uuid NOT NULL,
    requester_id uuid NOT NULL,
    receiver_id uuid NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT connections_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.education
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    institution character varying(255) COLLATE pg_catalog."default" NOT NULL,
    degree character varying(255) COLLATE pg_catalog."default",
    field_of_study character varying(255) COLLATE pg_catalog."default",
    start_date date NOT NULL,
    end_date date,
    current_education boolean NOT NULL DEFAULT false,
    description text COLLATE pg_catalog."default",
    grade character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT education_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.following
(
    id uuid NOT NULL,
    follower_id uuid NOT NULL,
    followed_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT following_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jobapplications
(
    id uuid NOT NULL,
    job_id uuid NOT NULL,
    applicant_id uuid NOT NULL,
    resume_url character varying(255) COLLATE pg_catalog."default",
    cover_letter text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    applied_at timestamp without time zone NOT NULL DEFAULT now(),
    last_updated timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT jobapplications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.joblistings
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    company_id uuid NOT NULL,
    company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    location character varying(100) COLLATE pg_catalog."default",
    employment_type character varying(50) COLLATE pg_catalog."default",
    workplace_type character varying(50) COLLATE pg_catalog."default",
    experience_level character varying(50) COLLATE pg_catalog."default",
    posted_at timestamp without time zone NOT NULL DEFAULT now(),
    expires_at timestamp without time zone,
    CONSTRAINT joblistings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.likes
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    post_id uuid,
    comment_id uuid,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT likes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    id uuid NOT NULL,
    sender_id uuid NOT NULL,
    receiver_id uuid NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    media_url character varying(255) COLLATE pg_catalog."default",
    media_type character varying(20) COLLATE pg_catalog."default",
    is_read boolean NOT NULL DEFAULT false,
    sent_at timestamp without time zone NOT NULL DEFAULT now(),
    is_deleted_by_sender boolean NOT NULL DEFAULT false,
    is_deleted_by_receiver boolean NOT NULL DEFAULT false,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'sent'::character varying,
    is_typing boolean DEFAULT false,
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    unseen_count integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.posts
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    company_id uuid,
    content text COLLATE pg_catalog."default",
    media_url character varying(255) COLLATE pg_catalog."default",
    media_type character varying(50) COLLATE pg_catalog."default",
    like_count integer NOT NULL DEFAULT 0,
    comment_count integer NOT NULL DEFAULT 0,
    repost_count integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    edited_at timestamp without time zone DEFAULT now(),
    visibility character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT posts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projectcontributors
(
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT projectcontributors_pkey PRIMARY KEY (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    project_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    institution character varying(255) COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    is_active boolean DEFAULT false,
    description text COLLATE pg_catalog."default",
    CONSTRAINT projects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.savedposts
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    post_id uuid NOT NULL,
    CONSTRAINT savedposts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.userprivacysettings
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    profile_visibility character varying(20) COLLATE pg_catalog."default" NOT NULL,
    show_email boolean NOT NULL DEFAULT false,
    allow_connection_requests boolean NOT NULL DEFAULT true,
    allow_messages_from_non_connections boolean NOT NULL DEFAULT false,
    show_active_status boolean NOT NULL DEFAULT true,
    CONSTRAINT userprivacysettings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.userprofiles
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    headline character varying(255) COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    location character varying(100) COLLATE pg_catalog."default",
    industry character varying(100) COLLATE pg_catalog."default",
    profile_picture_url character varying(255) COLLATE pg_catalog."default",
    cover_photo_url character varying(255) COLLATE pg_catalog."default",
    resume_url character varying(255) COLLATE pg_catalog."default",
    last_updated timestamp without time zone NOT NULL DEFAULT now(),
    num_connections integer DEFAULT 0,
    CONSTRAINT userprofiles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    user_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email_verified boolean NOT NULL DEFAULT false,
    is_premium boolean NOT NULL DEFAULT false,
    premium_expiry timestamp without time zone,
    is_active boolean NOT NULL DEFAULT true,
    reset_token character varying(255) COLLATE pg_catalog."default",
    reset_token_expiry timestamp without time zone,
    isadmin boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_user_name_key UNIQUE (user_name)
);

CREATE TABLE IF NOT EXISTS public.userskills
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    skill_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT userskills_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.workexperience
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date,
    current_job boolean NOT NULL DEFAULT false,
    description text COLLATE pg_catalog."default",
    location character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT workexperience_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.blockedusers
    ADD CONSTRAINT blockedusers_blocked_user_id_fkey FOREIGN KEY (blocked_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.blockedusers
    ADD CONSTRAINT blockedusers_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_blockedusers_user_id
    ON public.blockedusers(user_id);


ALTER TABLE IF EXISTS public.certifications
    ADD CONSTRAINT certifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_certifications_user_id
    ON public.certifications(user_id);


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id)
    REFERENCES public.comments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_comments_post_id
    ON public.comments(post_id);


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_comments_user_id
    ON public.comments(user_id);


ALTER TABLE IF EXISTS public.companypages
    ADD CONSTRAINT companypages_admin_user_id_fkey FOREIGN KEY (admin_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.connections
    ADD CONSTRAINT connections_receiver_id_fkey FOREIGN KEY (receiver_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_connections_receiver_id
    ON public.connections(receiver_id);


ALTER TABLE IF EXISTS public.connections
    ADD CONSTRAINT connections_requester_id_fkey FOREIGN KEY (requester_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_connections_requester_id
    ON public.connections(requester_id);


ALTER TABLE IF EXISTS public.education
    ADD CONSTRAINT education_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_education_user_id
    ON public.education(user_id);


ALTER TABLE IF EXISTS public.following
    ADD CONSTRAINT following_followed_id_fkey FOREIGN KEY (followed_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_following_followed_id
    ON public.following(followed_id);


ALTER TABLE IF EXISTS public.following
    ADD CONSTRAINT following_follower_id_fkey FOREIGN KEY (follower_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_following_follower_id
    ON public.following(follower_id);


ALTER TABLE IF EXISTS public.jobapplications
    ADD CONSTRAINT jobapplications_applicant_id_fkey FOREIGN KEY (applicant_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_jobapplications_applicant_id
    ON public.jobapplications(applicant_id);


ALTER TABLE IF EXISTS public.jobapplications
    ADD CONSTRAINT jobapplications_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.joblistings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_jobapplications_job_id
    ON public.jobapplications(job_id);


ALTER TABLE IF EXISTS public.joblistings
    ADD CONSTRAINT joblistings_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companypages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_joblistings_company_id
    ON public.joblistings(company_id);


ALTER TABLE IF EXISTS public.joblistings
    ADD CONSTRAINT joblistings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_comment_id_fkey FOREIGN KEY (comment_id)
    REFERENCES public.comments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_likes_comment_id
    ON public.likes(comment_id);


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_likes_post_id
    ON public.likes(post_id);


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_likes_user_id
    ON public.likes(user_id);


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_messages_receiver_id
    ON public.messages(receiver_id);


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_messages_sender_id
    ON public.messages(sender_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notifications_user_id
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.posts
    ADD CONSTRAINT posts_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companypages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_posts_company_id
    ON public.posts(company_id);


ALTER TABLE IF EXISTS public.posts
    ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_posts_user_id
    ON public.posts(user_id);


ALTER TABLE IF EXISTS public.projectcontributors
    ADD CONSTRAINT projectcontributors_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.projectcontributors
    ADD CONSTRAINT projectcontributors_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_projects_user_id
    ON public.projects(user_id);


ALTER TABLE IF EXISTS public.savedposts
    ADD CONSTRAINT savedposts_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.savedposts
    ADD CONSTRAINT savedposts_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_savedposts_user_id
    ON public.savedposts(user_id);


ALTER TABLE IF EXISTS public.userprivacysettings
    ADD CONSTRAINT userprivacysettings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_userprivacysettings_user_id
    ON public.userprivacysettings(user_id);


ALTER TABLE IF EXISTS public.userprofiles
    ADD CONSTRAINT userprofiles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_userprofiles_user_id
    ON public.userprofiles(user_id);


ALTER TABLE IF EXISTS public.userskills
    ADD CONSTRAINT userskills_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_userskills_user_id
    ON public.userskills(user_id);


ALTER TABLE IF EXISTS public.workexperience
    ADD CONSTRAINT workexperience_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_workexperience_user_id
    ON public.workexperience(user_id);

END;